{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inbound-task-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "inbound-task-api.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
      name: http
  selector:
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
