{{ if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.saName }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.config.serviceAccountIamRole }}
  annotations:
    "eks.amazonaws.com/role-arn": {{ .Values.config.serviceAccountIamRole }}
  {{- end }}
  labels:
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end }}