name: "maven_depenedency_submission"

on:
  workflow_dispatch:

jobs:
  maven_depenedency_submission:
    name: maven_depenedency_submission
    runs-on: ubuntu-latest
    permissions: read-all|write-all
#    permissions:
#      actions: read
#      contents: read
#      security-events: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

#    - name: Build with Maven
#      run: mvn clean install -DskipTests

    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
